name: http_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http_delegate:
    path: ../
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  simple_json: ^2.2.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
